# Generated by Django 2.2.5 on 2019-09-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190920_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknumber',
            old_name='sibn_10',
            new_name='isbn_10',
        ),
        migrations.RenameField(
            model_name='booknumber',
            old_name='sibn_13',
            new_name='isbn_13',
        ),
    ]
